version: "2"
linters:
  default: standard
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - goheader
    - mnd
    - lll
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - unused
    - whitespace
    - wrapcheck
    # - gochecknoglobals
    # - paralleltest
    # - testpackage
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - funlen
          - dupl
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: original
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
            - pkg: github.com/sirupsen/logrus
    dupl:
      threshold: 150
    funlen:
      lines: 50
      statements: 35
    goconst:
      min-len: 2
      min-occurrences: 3
      match-constant: true
      numbers: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 80
    gocyclo:
      min-complexity: 10
    godox:
      keywords: # default keywords are TODO, BUG, and FIXME
        - BUG
        - FIXME
        - HACK
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 150
      tab-width: 2
    misspell:
      locale: UK
      ignore-rules:
        - color
    nestif:
      min-complexity: 6
    nolintlint:
      # report any unused nolint directives
      allow-unused: false
      # require an explanation for nolint directives
      require-explanation: true
      # require nolint directives to be specific
      #   about which linter is being skipped
      require-specific: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
